version: '3'
services: 
    dst:
        tty: true
        container_name: dst
        ports:
            - "10999-11000:10999-11000/udp"
            - "12346-12347:12346-12347/udp"
        build: .
        volumes: 
            - ./klei:/home/steam/.klei